sample_fonts = [       
    "Al Bayan Bold",                        
    "Al Bayan Plain",
    "Andale Mono",
    "Arial Black",
    "Arial Bold Italic",
    "Arial Bold",
    "Arial Italic",
    "Arial Narrow Bold Italic",
    "Arial Narrow Bold",
    "Arial Narrow Italic",
    "Arial Narrow",
    "Arial Rounded Bold",
    "Arial Unicode",
    "Arial",
    "Ayuthaya",
    "Big Caslon",
    "Brush Script",
    "Impact",
    "Lucida Grande",
    "Menlo-Regular",
    "Monaco",
    "New York",
    "Skia"
]